### ISSUE TITLE
Autoincrement minor and major if patch or minor overcome specific value

### ISSUE THREAD

**Issue by antoniogiordano** [radubrehar/versiony#8]
Hi,

I created a script that every time it runs it updates a version number with this library.
But, since there is no logic behind, it just upgrades the patch number with patch().
I think it should be useful to have a specific method for incrementing in a smartest way, like, if the version is 3.45.999, doing something like .autoPatch(999) the result should be 3.46.0.
The parameter passed to autoPatch (and autoMinor() as well) should be the max value before resetting patch/minor and increasing minor/major.
Could it be useful for anybody else?
I can write a logic behind this, but since I need to use in many projects I want to know if you are interested in this pull request or I should fork it.

Thanks.

**Comment by radubrehar** [comment]
Hi Antonio

I'm no longer maintaining the project - also gave the npm module to someone else, please see https://www.npmjs.com/package/versiony. It's better to continue the development to the repo the npm package is pointing to.

Thanks

**Comment by antoniogiordano** [comment]
Thanks radubrehar, I pull request that ;-)
